### ISSUE TITLE
Markdown support for Text wrapping images

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#102]
The following syntax should be supported for permitting text wrapping around images:

```
![On the left: An example image](/path/to/image.svg)
```

"On the left:" could read "To the left:", "See left:", or even just "Left:".  In the case of "left," the image will be positioned to the left with text wrapping to its right.  In the case of "right," the image will be positioned to the right with text wrapping to its left.

Images with alt text that doesn't indicate left or right should be positioned center with 100% block width.

**Comment by micchickenburger** [comment]
I don't think any javascript is even needed for this.  We could just use CSS selectors:

```
img[alt*="Left:" i] { float: left; }
img[alt*="Right:" i] { float: right; }
```

Of course, `p` elements would need to have that `float: clear;` CSS reset declaration removed for this to work.

**Comment by eoghanTadhg** [comment]
Any updates on this issue @micchickenburger ?
Shall I proceed to add the css as you've provided?

**Comment by micchickenburger** [comment]
Yes, please @eoghanTadhg.
