### ISSUE TITLE
Listservs accessible when not logged in

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#106]
Are listservs only accessible when logged-in? Can we make it so that listservs are visible but maybe you do need to log in in order to sign in?

**Comment by micchickenburger** [comment]
Where would you have them visible?  Right now they're under the profile template.  You wouldn't see a profile template without first having a profile.  :)

**Comment by micchickenburger** [comment]
The listserv page can be linked within any of the sections, as deemed appropriate by staff.  There's no sense in showing listserv subscriptions to a non-logged-in user.

**Comment by peterfiala** [comment]
By listserv page, do you mean https://beta.wcasa.org/account/subscriptions? This I can only see if I'm logged in.
