### ISSUE TITLE
Listing of Regular Events

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#108]
Is there a way to have a listing of regular events, including this list. Or however it makes most sense:
    Director's Meetings 
    Sexual Assault Victim Advocacy School (SAVAS)
    Sexual Assault Awareness Month (SAAM)
    Survivors & Allies Task Force Meetings
    Voices of Courage Awards Ceremony/Luncheon
    Wrap Around the Capitol
    Paths to Healing
    Northern Training
    Annual Meeting

**Comment by eoghanTadhg** [comment]
**Reoccurring events?**

**Comment by peterfiala** [comment]
The list of events above are ones that repeat 2-4 times/year. On the current site we have a standing page for each event and then I just update the date. With the new site there are just the individual event dates. I was wondering if there could be links somewhere that could link to these reoccurring events or how best to handle it. For instance, if people wanted to see what the Northern Training is all about but didn't know the last date or date coming up. Does that make sense?

**Comment by micchickenburger** [comment]
We could add a feature that allows you to create a new event from an existing one, like a copy.

**Comment by peterfiala** [comment]
Sounds good.

**Comment by micchickenburger** [comment]
Superseded by #213
