### ISSUE TITLE
Events: Permit searching

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#109]
Is this best done in the front page 'slides' and can we save and link to them though they don't appear on the front page? Or is there another solution?

What I'd like to do is have a page like the Denim Day page accessible and linkable even after the event passes. See http://www.wcasa.org/pages/Events-SAAM-DenimDay.php to get an idea.

**Comment by eoghanTadhg** [comment]
Hi Peter,

I think any thing you'd like to feature is best suited in the slider. 
It could link to the event pane within the event section.
-or-
It could move to a standalone page.
We do have a standalone page template for published articles found in the 'In the News' section.

Micah what do you think?
@micchickenburger  @peterfiala

**Comment by micchickenburger** [comment]
The events section contains event details.  For example, you could add an event on September 21, 2015 called "Denim Day."  It would be linkable as such:  `/events/2015/september/denim-day/`.  It could also just be read as `/events/denim-day/`, but if there has been more than one event with the same name, there's ambiguity here and I'd likely program the logic to pick the most recent event.

**Comment by peterfiala** [comment]
That makes sense. So if they search ‘Denim Day’ that page will come up. I’ll just have to make sure I put in more direct links to events. Its fine if someone searches for an event that the most recent one comes up. If someone is searching for an event though, would the search come up with 2016, 2015, etc.?

**Comment by micchickenburger** [comment]
Yes, users can search for events by title.  The result would show the month and year beside/under the title.

**Comment by micchickenburger** [comment]
This has been implemented through commit 46a9e29cb9f4b21220dd41e5b99b82ab1b9aec16
