### ISSUE TITLE
Link to Action Alerts & Updates

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#111]
Please link subpage 'Action Alerts & Updates' under Policy & Law to 'Action Alerts' under 'News. By the way, is this too small an issue to be putting on Github?

See http://beta.wcasa.org/what-we-do/policy-&-law/action-alerts-&-updates#

**Comment by micchickenburger** [comment]
Oh boy.  This is actually a big deal.  It breaks away from the schema for the work section.  Are you willing to compromise and add text on the page that explains what action alerts are, and then links to the action alerts section?  Action alerts of course doesn't have a link yet, but I presume it would be `/newsroom/action-alerts`.

**Comment by peterfiala** [comment]
At first I thought we could save some time by only having to update the Action Alerts under News page. I think we could add text to explain what action alerts are, it would just be that we have to update the action alerts in two places. No ideal but we can work around it.

**Comment by micchickenburger** [comment]
No, I mean just have text describing Action Alerts.  For example:

> ### Action Alerts
> 
> Action Alerts are notices or updates regarding time-sensitive matters, such as State and Federal legislation.  Action Alerts may call upon the community to contact lawmakers to help WCASA achieve the social change necessary to end sexual violence.
> 
> Action Alerts can be accessed from the Newsroom, or by clicking [here](/newsroom/action-alerts).

So this section would be in the What We Do area, however you nest it.  Does that make sense?  There's no need to duplicate the information.

**Comment by peterfiala** [comment]
Oh yeah, that makes sense
