### ISSUE TITLE
Create Feedback package

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#122]
Users should be able to leave feedback.  We could throw something on the side of the screen `position: fixed; right: 0; top: 50%;` as an example.  It could have a fontawesome icon and the text "Feedback" or something.  Clicking would bring out feedback form, which can be an autoform from the feedback simpleschema, which would need to be created.

**Comment by eoghanTadhg** [comment]
When are we hoping to build this?

**Comment by micchickenburger** [comment]
This was implemented a while ago.
