### ISSUE TITLE
Hide Components for Beta Release

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#123]
Before the beta release, we need to hide the following incomplete components:
- Profile -> Library Activity
- News -> Annual Reports
- News -> Press & Media Kits
- Learning Center -> Library
- Learning Center -> Stats & Data

**Comment by eoghanTadhg** [comment]
This required adding a new width of `500` to the LESS variable `@offCanvasWidths` in options.import.less. Then in aside.js we comment out the object pertaining to the section and then we change the width of the parent object in this file to `500`. The `500` is not required, but we did not require as much width when we trim down the section tabs.
