### ISSUE TITLE
Post Template Header can be Overwhelming

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#127]
The orange header for Action Alerts, Press Releases, etc. can be very overwhelming with long titles.

![screen shot 2016-10-03 at 6 53 13 pm](https://cloud.githubusercontent.com/assets/4521230/19058192/e9af3ee4-899a-11e6-93a4-404d67973cba.png)

**Comment by micchickenburger** [comment]
What do you think, @eoghanTadhg?  Seems bright to me on my 1080p display, and takes up a good size of the screen.

**Comment by eoghanTadhg** [comment]
Agreed. Lets tone that down.

**Comment by eoghanTadhg** [comment]
This has been corrected.
