### ISSUE TITLE
Please Style the Profile Tab

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#128]
Conveniently found at `/account/profile/` when logged in.  I've connected the profile fields, but it is a bit hideous.  AutoForm does follow Bootstrap styles, in case you're familiar with that.

**Comment by eoghanTadhg** [comment]
closed with commit #7d108d0.
A fix for launch sake has been placed where we grab a custom select template.
Defaults will still need to be designed and attributed, but the profile tab now looks functional.
