### ISSUE TITLE
Work Section Content Accordions

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#129]
We will need to implement the collapsed content we talked about in the work section.

How will we be going about doing this? @micchickenburger 

I will comment the commit on this issue once styles for details/accordion are complete.

**Comment by micchickenburger** [comment]
Is this essential for Beta release?  There's not much time left.

**Comment by eoghanTadhg** [comment]
@micchickenburger, I think visually it works as is. Certainly an enhancement we could add.

**Comment by micchickenburger** [comment]
@eoghanTadhg Is this still an issue?

**Comment by micchickenburger** [comment]
Is this related?  Issue #100

**Comment by eoghanTadhg** [comment]
This was when we talked about further collapsing content within the work section, which I do not believe is a necessary UX.
