### ISSUE TITLE
Creating New Section

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#130]
I went to try to create a new section under 'What We Do' and it created a page up a level. You'll see there are four 'unnamed pages' there now because I kept clicking when I didn't see a section come up (under 'What We Do')

**Comment by micchickenburger** [comment]
Removed extra pages.

**Comment by peterfiala** [comment]
Thanks.

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc
