### ISSUE TITLE
Delete Function in Newsroom

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#132]
The function to delete entries in all sections of the newsroom is not enabled. (Maybe you know this). When I move down on the page the same 5 or 6 delete icons move down and I don't think they are connected with particular items.

**Comment by micchickenburger** [comment]
Yep, we are aware of this one.

**Comment by peterfiala** [comment]
Okay thanks

Sent using OWA for iPhone

**Comment by eoghanTadhg** [comment]
@micchickenburger  These are going to need to be added on a per line-item basis, not an admin controls element. What is the best way to proceed?

**Comment by eoghanTadhg** [comment]
Retract that previous statement. that is how they are. will take care of.
