### ISSUE TITLE
Adding Section Under 'Who We Are'

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#140]
When I add a section under 'Who We Are', the section instead adds to the top page level, rather than the a subpage. What I'd like to do is add a page called 'Membership' under 'Who We Are'

**Comment by micchickenburger** [comment]
Yes, issue acknowledged.

**Comment by peterfiala** [comment]
Thanks.

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
2801 W. Beltline Hwy., Ste 202, Madison, WI 53713
Telephone: 608-257-1516; Direct: 608-284-5494
Fax: 608-257-2150
Website: www.wcasa.orghttp://www.wcasa.org/
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc
