### ISSUE TITLE
Parts of WCASA under 'Who We Are'

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#141]
Would you be able to get rid of this descriptor? It seems like does not link to a page and might confuse people. Thanks!

**Comment by micchickenburger** [comment]
It shouldn't be removed; rather, it should perhaps stand out a little more as a header, which is what it is.  Links by themselves would make the column feel naked.

@eoghanTadhg can you maybe introduce an underline and remove the on-hover cursor pointer?

**Comment by peterfiala** [comment]
We thought 'The Parts of WCASA', the text, was a little awkward. I don't think we're against having some text there, maybe just changing what is currently there. I'll see what other suggestions there are. Making it stand out more makes sense to me.

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
2801 W. Beltline Hwy., Ste 202, Madison, WI 53713
Telephone: 608-257-1516; Direct: 608-284-5494
Fax: 608-257-2150
Website: www.wcasa.orghttp://www.wcasa.org/
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc
