### ISSUE TITLE
Service Provider Map

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#143]
A few questions: 
- Is there a way to make the pins not appear so big and make the map appear cluttered?
- Can we denote non-SASPs with different colored pins, maybe orange to match the other color of our logo?

**Comment by micchickenburger** [comment]
The only non-SASP on the map is WCASA, which is in a different color.

**Comment by micchickenburger** [comment]
@eoghanTadhg, smaller pins on the state-wide view?

**Comment by peterfiala** [comment]
Thanks Eoghan. Are they subtly smaller? The reason for smaller being that if there are more pins we would like it to appear less cluttered.

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
2801 W. Beltline Hwy., Ste 202, Madison, WI 53713
Telephone: 608-257-1516; Direct: 608-284-5494
Fax: 608-257-2150
Website: www.wcasa.orghttp://www.wcasa.org/
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc

**Comment by peterfiala** [comment]
We would like to add agencies that are non-SASPs, like HAWA, HAFA, Freedom Inc., etc.

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc

**Comment by eoghanTadhg** [comment]
Hey Peter, you may observe a few of the closed issues not appearing on the dev server as they will need to be merged from my development branch. I'm sure Micah can give you the heads up when that happens.
You will observe numerous improvements/fixes when migrated.
Including this issue, I've made them about 30% smaller. They were indeed a little too big.

**Comment by peterfiala** [comment]
Got it, thanks! That makes sense.

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc
