### ISSUE TITLE
Adjust Staff Photos

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#146]
I swapped out a few photos but now the perspective is off. Could you adjust please?

Thanks,
Peter

**Comment by micchickenburger** [comment]
Images in this section must be 200x200px.  If they aren't square, they'll be stretched.  What's the difference between the new ones and the old ones?

**Comment by peterfiala** [comment]
No difference. All the photos I uploaded were roughly 120 x 152. I uploaded the same photos because I had to redo some of the names (deleting them was the only way to do that), but just like the first ones I uploaded, they were distorted. Let me know what I should do to any of the photos.

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
2801 W. Beltline Hwy., Ste 202, Madison, WI 53713
Telephone: 608-257-1516; Direct: 608-284-5494
Fax: 608-257-2150
Website: www.wcasa.orghttp://www.wcasa.org/
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc
