### ISSUE TITLE
En Espanol

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#150]
Would you be able to add a page called 'En Espanol' on the same level as 'What We Do' and 'Who We Are'?

**Comment by peterfiala** [comment]
In the past few weeks, staff here was looking through other websites to see how they laid out text in Spanish. We don't feel that Google translate is adequate. We were wondering what would make sense and where to have an 'En Espanol' link on the front page. Would it be most visible on the level of 'What We Do' or on the same level as Donate, Twitter, etc.

**Comment by micchickenburger** [comment]
We will be implementing full internationalization in the future.  Please don't create "En Español" pages.

**Comment by peterfiala** [comment]
Maybe we can discuss this further as I'm not sure what full internationalization is. The concern is that automatic translation is inaccurate.

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
2801 W. Beltline Hwy., Ste 202, Madison, WI 53713
Telephone: 608-257-1516; Direct: 608-284-5494
Fax: 608-257-2150
Website: www.wcasa.orghttp://www.wcasa.org/
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc
