### ISSUE TITLE
Twitter Link

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#151]
Wondering if it is possible to change the Twitter to an icon, just like Facebook and YouTube.

**Comment by micchickenburger** [comment]
The Twitter feed is a sidebar item, like newsroom and learning center.  Facebook and YouTube are just icons because they don't have sidebar items; they're just links.

**Comment by peterfiala** [comment]
Thanks for the explanation. Is there a way to change the name 'Twitter' should we need to / want to? I'm wondering if there is better name for it since the Twitter icon is already there.

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
2801 W. Beltline Hwy., Ste 202, Madison, WI 53713
Telephone: 608-257-1516; Direct: 608-284-5494
Fax: 608-257-2150
Website: www.wcasa.orghttp://www.wcasa.org/
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc
