### ISSUE TITLE
Mobile Tab Behavior (Menu + All)

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#169]
tabs.html has a spacebars condition to set the tab to to `aria-hidden="false"` on lines 19 and 48.
We need `isFirst` to return `aria-hidden="true"` if the window width < 768.

Thoughts on the best way to accomplish this?

![image](https://cloud.githubusercontent.com/assets/5591794/20252790/45637408-a9da-11e6-9524-18f936c4a4d5.png)

**Comment by micchickenburger** [comment]
Spacebars conditions leave a lot to be desired.  I'd recommend using a helper for this:

```
// tabs.html
<article data-id="{{id}}" aria-hidden="{{#if hidden}}true{{else}}false{{/if}}" data-editable="{{editable}}" class="{{#if isAdmin}}admin{{/if}}">

// tabs.js
Template.tabs.helpers({
  /**
   * @summary Determines whether or not to show the tab by default
   * @function
   * @returns {boolean}
   */
  hidden: () => !Template.currentData().isFirst && window.innerWidth < 768,
});
```

**Comment by eoghanTadhg** [comment]
Also need to check links behavior from outside the menu.

**Comment by eoghanTadhg** [comment]
And deep linking.

**Comment by eoghanTadhg** [comment]
Forms are dark blue for some reason.

**Comment by eoghanTadhg** [comment]
Although isFirst doesn't seem to be returning true/false correctly.

**Comment by eoghanTadhg** [comment]
@micchickenburger : is it possible to have the `data-id` on tabs to match the URL string?
Perhaps  not. But I've been having trouble with collapsing tabs on mobile and have placed a jquery solution on the coming branch which hides the tabs after being rendered if their data-id does not match the deep-link URL. (I know, not very elegant... Perhaps you can help me with this one) Otherwise lets talk some more. However deep-linking aside: it is essential for all tabs to be collapsed in order for the mobile menu to work properly.

Stay tuned for the pull request...

**Comment by eoghanTadhg** [comment]
Need to make sure this doesn't affect the masthead which should have it's first tab open.

**Comment by eoghanTadhg** [comment]
Mobile tabs have been configured to work properly.
