### ISSUE TITLE
Masthead Design Improvements

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#170]
Hey @micchickenburger ,
I see the masthead has been updated with some new content.
Is this still in progress, do we have background image selections?
I want to enhance this design a little bit, but it will help to see what the assets/final content will be.

**Comment by eoghanTadhg** [comment]
See the pull-request for `mastheadImprovements`.

**Comment by micchickenburger** [comment]
I merged pull request #172 yesterday.  @peterfiala should determine whether any background images should change.

**Comment by peterfiala** [comment]
Let's leave the background images the same right now.

**Comment by eoghanTadhg** [comment]
@micchickenburger  , Is beta.wcasa.org displaying the most current `wcasa-dev` branch?
It seems the masthead updates may have not merged correctly. For instance the `ul` should appear as a comma delimited list, margins not updated and text content not updated. Thoughts?

@peterfiala , Peter we will need to update those images as we do not own the rights to them and they were only there as placeholders.

**Comment by peterfiala** [comment]
Ah haa…might something like this work?

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc

**Comment by micchickenburger** [comment]
@eoghanTadhg Nope, the https://beta.wcasa.org site is actually the production instance.  The staging instance is https://wcasa-staging.herokuapp.com

**Comment by peterfiala** [comment]
Thanks.

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]http://www.facebook.com/wcasa [link to wcasa's Twitter feed] http://twitter.com/wcasa_vpcc  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] http://www.youtube.com/user/wcasavpcc

**Comment by eoghanTadhg** [comment]
This has been resolved.
