### ISSUE TITLE
Work section styling problem when uneven number of sections

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#180]
When there are neither four nor eight sections added in the work section, there is a display flaw:

<img width="1129" alt="screen shot 2016-11-19 at 2 54 19 pm" src="https://cloud.githubusercontent.com/assets/4521230/20458431/a0cdae1e-ae6a-11e6-8ad1-4fd58412893f.png">

**Comment by eoghanTadhg** [comment]
Redundant with #344
