### ISSUE TITLE
Event link 'online'

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#186]
I entered in information for our event SAVAS on November 14-17, added a location and page link but it shows 'online' as the link. I thought this was only for the external links but maybe I missed something.

**Comment by micchickenburger** [comment]
Looks fine to me when I just checked.  There were more than a month's worth of changes that I only just pushed to the beta site tonight.  It must have been a bug I already corrected.  :)

**Comment by peterfiala** [comment]
Yeah it looks different now and fixed. Thanks!

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]<http://www.facebook.com/wcasa> [link to wcasa's Twitter feed] <http://twitter.com/wcasa_vpcc>  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] <http://www.youtube.com/user/wcasavpcc>
