### ISSUE TITLE
Way to Archive Webinars

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#188]
Webinar registration is run through GoToMeeting. Once a webinar is done, it is archived on YouTube. Is there a way to just list that the webinar happened on the date it did, but remove the times? Currently 'online' links to YouTube. Is there a way to disable that link entirely after an event passes or have the option of changing it (I would change it to say 'see recording' or something like that)

For other events the times can stay.

**Comment by micchickenburger** [comment]
I changed the webinar text.  What do you think?

**For events in the Future:**  Join Webinar
![screen shot 2017-05-27 at 12 44 38 am](https://cloud.githubusercontent.com/assets/4521230/26518427/efacfd9c-4275-11e7-9b4e-63acb0be9aff.png)

**For events in the Past:**  View Recorded Webinar
![screen shot 2017-05-27 at 12 44 23 am](https://cloud.githubusercontent.com/assets/4521230/26518430/f6d1f2f8-4275-11e7-9730-1b6a4005b2e3.png)

**Comment by peterfiala** [comment]
I think its very clear now, awesome!

Peter
