### ISSUE TITLE
Awareness Months in Events

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#189]
Is there a way to make the times of an event optional? Say in the case of DV Awareness Month, which lasts all October. I'm fine if the event is really listed only on October 1st since I know it would be difficult to have it listed on all 31 days of the month.

**Comment by micchickenburger** [comment]
We need to be able to have events that last a month that don't appear as events.  Perhaps a banner at the top of the event details section for all events within that month, or something?  @eoghanTadhg, thoughts?

**Comment by peterfiala** [comment]
Yeah, a banner sounds good to me. Sometimes we have up to 4 or 5 awareness months or weeks. Awareness days could just be put on the day as an event I would imagine.
