### ISSUE TITLE
Provider List

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#197]
When adding phone numbers for providers, we are only able to list 1 crisis number. Some providers do have more than one and also one that they can text.

**Comment by peterfiala** [comment]
When adding satellite office, and selecting the parent location, the other satellite location is listed as a possible parent.

**Comment by micchickenburger** [comment]
Sure, why not?  ;-)  Just select the proper one.

**Comment by peterfiala** [comment]
Okay thanks

Sent using OWA for iPhone
________________________________

**Comment by micchickenburger** [comment]
I'm confused about the multiple crisis lines.  How does a victim know which to call?

**Comment by peterfiala** [comment]
Hey Jasmine, which county / program had multiple crisis lines?

Thanks,
Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]<http://www.facebook.com/wcasa> [link to wcasa's Twitter feed] <http://twitter.com/wcasa_vpcc>  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] <http://www.youtube.com/user/wcasavpcc>

**Comment by peterfiala** [comment]
Friends of Abused Families
Embrace
Advocates of Ozaukee

These are the ones I know for sure, but there could be more!

Hope this helps,
Jasmine McDonald
University of Wisconsin-Whitewater
WCASA Intern



Wisconsin Coalition Against Sexual Assault (WCASA)
2801 W. Beltline Hwy., Ste 202, Madison, WI 53713
Telephone: 608-257-1516; Direct: 608-284-5494
Fax: 608-257-2150
wcasa.org
Creating the Social Change Necessary to End Sexual Violence



________________________________
From: Peter Fiala
Sent: Monday, January 30, 2017 10:14:41 AM
To: enove/Thriver; enove/Thriver
Cc: Author; Jasmine McDonald
Subject: RE: [enove/Thriver] Provider List (#197)

Hey Jasmine, which county / program had multiple crisis lines?

Thanks,
Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]<http://www.facebook.com/wcasa> [link to wcasa's Twitter feed] <http://twitter.com/wcasa_vpcc>  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] <http://www.youtube.com/user/wcasavpcc>
