### ISSUE TITLE
Hide 'Index' when there are no sublevels?

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#204]
Where there are no third level links, is this possible?

**Comment by micchickenburger** [comment]
@peterfiala Can you provide a screenshot of what you mean?

**Comment by micchickenburger** [comment]
![screen shot 2017-05-26 at 2 12 19 pm](https://cloud.githubusercontent.com/assets/4521230/26509219/78a138e2-421d-11e7-8ec0-753d5b89a908.png)
