### ISSUE TITLE
Staff Photos not Loading

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#206]
I deleted and added a few staff photos. When I added an entry, the photos weren't showing up.,

**Comment by micchickenburger** [comment]
<img width="1120" alt="screen shot 2017-05-25 at 7 50 24 pm" src="https://cloud.githubusercontent.com/assets/4521230/26476316/6c2a7e2e-4183-11e7-8f26-21f926e0f5f1.png">

**Comment by micchickenburger** [comment]
The missing images source to C:\fakepath\name.jpg.  Looks to me like a Chrome upload problem.
