### ISSUE TITLE
No Line Break after Bulletted List

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#207]
The paragraph after a bulletted list has no line break between, as demonstrated here: https://beta.wcasa.org/service-providers

**Comment by micchickenburger** [comment]
@peterfiala Are you referring to the list of offices in this screenshot?
<img width="1265" alt="screen shot 2017-05-25 at 7 47 40 pm" src="https://cloud.githubusercontent.com/assets/4521230/26476257/183a9a9c-4183-11e7-9e6f-2a94f4efe8eb.png">

**Comment by peterfiala** [comment]
Sorry, linked the wrong page. i'll keep looking!

**Comment by micchickenburger** [comment]
![screen shot 2017-05-26 at 2 51 52 pm](https://cloud.githubusercontent.com/assets/4521230/26510425/e99729a8-4222-11e7-89c5-85f8f0d8e2d2.png)

Bullet items should have less spacing between themselves; last item should have extra bottom margin, perhaps.  Or if problem only occurs with headers, maybe headers should just have greater top margin.  Up to you @eoghanTadhg
