### ISSUE TITLE
Staff & BoD Sections Display Problems

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#26]
![screen shot 2016-03-05 at 8 04 56 pm](https://cloud.githubusercontent.com/assets/4521230/13551859/b5be1094-e30d-11e5-83d9-4973ab2ae150.png)
![screen shot 2016-03-05 at 8 05 07 pm](https://cloud.githubusercontent.com/assets/4521230/13551860/b5beb562-e30d-11e5-88f4-b9dca48adc8e.png)

**Comment by eoghanTadhg** [comment]
This has been resolved.
