### ISSUE TITLE
Learning Center / Infosheets - Date One Day Prior 

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#268]
I noticed when I entered in a publishing date, the date that shows up is one day prior.

**Comment by micchickenburger** [comment]
Good eye!

**Comment by micchickenburger** [comment]
The problem was that news and learning center items were being added to the database in UTC, but the web browser was rendering the time in the local time zone.  Central time is UTC-5 hours, which puts you a day back.

**Comment by peterfiala** [comment]
Welcome! Glad we caught it and thanks for fixing.


Peter


Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
2801 W. Beltline Hwy., Ste 202, Madison, WI 53713
Telephone: 608-257-1516; Direct: 608-284-5494
Fax: 608-257-2150
Website: www.wcasa.org<http://www.wcasa.org/>
[link to wcasa's Facebook page]<http://www.facebook.com/wcasa> [link to wcasa's Twitter feed] <http://twitter.com/wcasa_vpcc>  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] <http://www.youtube.com/user/wcasavpcc>
________________________________
