### ISSUE TITLE
Adding Document

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#284]
Hey there, I added text to https://beta.wcasa.org/what-we-do/systems/medicalreproductive-health 

Here is the document location: http://www.wcasa.org/file_open.php?id=1553

Do I need put in a ticket every time I want to link a new document while we're in this transitional period?

Thanks,
Peter

**Comment by eoghanTadhg** [comment]
Note sure what this is specifically pertaining to. Thoughts @micchickenburger ?

**Comment by peterfiala** [comment]
Micah downloaded all of the documents from our current website, but when I go to make changes or add documents in this interim time I thought I needed to email them. I'm guessing the code you wrote Micah to download those documents doesn't account for changes?
