### ISSUE TITLE
Links not working in Evaluation Sections

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#333]
The links at the bottom are not working on https://beta.wcasa.org/what-we-do/evaluation/select-indicators

Advocacy Tools
Prevention Tools
Other Tools (Community Assessment, Trauma Informed Care & Volunteer Training)

![image](https://user-images.githubusercontent.com/22227365/32969684-ac7d5020-cbab-11e7-95d0-f2fb323df27b.png)

**Comment by micchickenburger** [comment]
Strangely, none of the download links in the work section work anymore.  Some script is probably doing a `event.preventDefault()` for `a` elements `onClick`.

**Comment by peterfiala** [comment]
What could be the issue? At first I thought it might be the browser I was using.

Peter

Peter Fiala
Technology & Events Coordinator
Wisconsin Coalition Against Sexual Assault (WCASA)
[link to wcasa's Facebook page]<http://www.facebook.com/wcasa> [link to wcasa's Twitter feed] <http://twitter.com/wcasa_vpcc>  [https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8fWOIOHiKkDuBEon9eoc4_Rkp-EW-KLKXvst0VMmewXeOO9ZF] <http://www.youtube.com/user/wcasavpcc>
