### ISSUE TITLE
Hover effect on various input fields is inconsistent

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#35]
The hover effect established by the following code does not apply to email, search, or password input fields, which can make the hover effect feel inconsistent, such as in the profile tab under Account Details.

    form .styledSelect:hover, form .cvv2:hover, form input[type=text]:hover {
        background-color: #4c5d67;
    }

Furthermore, disabled fields should not have a hover effect.

    <input type="text" value="Text" disabled />

**Comment by micchickenburger** [comment]
These are defined in forms.import.less on line 249, btw.

**Comment by eoghanTadhg** [comment]
Closed as no longer applicable.
