### ISSUE TITLE
Columbia County

### ISSUE THREAD

**Issue by peterfiala** [enove/NoSLB#350]
This county does not show up in the dropdown for counties in Get Help

**Comment by micchickenburger** [comment]
That means there aren't any providers that service that county.

**Comment by peterfiala** [comment]
It is a county that it serviced by Hope House. No office, just a P.O. Box. I just added it to their profile. Hopefully that is the last discrepancy in the list!

Columbia County

Hope House
PO Box 557
Baraboo, WI 53913
Phone: (608) 356-9123
Crisis Line: (800) 584-6790
TTY: (800) 584-6790
Email: ellena@hopehousescw.org
Website: http://www.HopeHousescw.org
Facebook: https://www.facebook.com/hopehousescw Facebook Icon

Counties Served: Adams, Columbia, Sauk, Juneau, Marquette
