### ISSUE TITLE
What We Do Section missing some formatting

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#42]
In the What We Do section, it looks like `<h3>` elements have no top margin, and `<li>` elements have no bullet point.  That's what's causing the formatting to look a bit off.  In reality, some of the sections are actually well-formed from markdown, such as the Advocacy page; it just doesn't look like it because of some missing styles.

**Comment by eoghanTadhg** [comment]
This has been closed as marked as redundant with #22 .
