### ISSUE TITLE
Unable to display currentUser.name etc. on profile page

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#75]
I'm trying to set the value to display dynamically based on the JS object I've setup however I am having trouble displaying a currentUser variable dynamically based on the object "value" value.
@micchickenburger : any thoughts on this one?

**Comment by micchickenburger** [comment]
Users are handled by Meteor.  Check out the utility nav JS to see how I did
it in the past.  I think it was `Meteor.currentUser.profile.firstName`.

**Comment by eoghanTadhg** [comment]
Hey, thanks for responding! 
I figured it out, I just needed to put your clever functions into the property value slots in the data array.
