### ISSUE TITLE
Does the listServSubscribe return 'undefined' on local environments?

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#76]
I'm noticing a JS error on my local when a listserv checkbox is interacted with. Is this expected?

`subscriptions.js:121 Uncaught ReferenceError: listServSubscribe is not defined`

**Comment by eoghanTadhg** [comment]
Nevermind! Corrected. However I do see access not allowed on localhost.

**Comment by micchickenburger** [comment]
Yes, on local unexpected behavior may result due to differences I the ways
browsers handle cross-site scripting.  We can only test the listserv
functionality from beta.
