### ISSUE TITLE
Connect on Register/Sign In Data Schema

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#77]
Not sure how far you brought these @micchickenburger .
I made best efforts on making templates more reactive and introduced a basic schema.
We should connect on these.
I'd like to discuss:
- Register button is currently disabled
- How far along is "register"
- Error handling & for all forms for that matter

**Comment by micchickenburger** [comment]
We're using AutoForm and SimpleSchema to address these concerns.
