### ISSUE TITLE
Make Library Components Reactive

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#78]
Pending explicit direction from client on what meta-data makes up the library.

**Comment by eoghanTadhg** [comment]
@micchickenburger : not sure when this type of meta will be defined.

**Comment by eoghanTadhg** [comment]
This one is in your court @micchickenburger  at defining what the library will be content and meta wise. Let me know once WCASA has defined.

**Comment by micchickenburger** [comment]
Handled in Pull Request #246
