### ISSUE TITLE
Suggest 'Date/FriendlyDate' feature be moved to a more globalized function for reuse

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#81]
I can explain my thinking further when we connect after the chandelier update.
This is not essential, but I think may be an improvement.

**Comment by eoghanTadhg** [comment]
Also may need some help, I'm having trouble displaying the 'friendly date'

**Comment by micchickenburger** [comment]
We can see about adding it to the core package.

**Comment by micchickenburger** [comment]
This was done a while ago.  The `friendlyDate` helper can be found in the `thriver-core` package under `lib/client/ui/helpers-spacebars.js`.
