### ISSUE TITLE
Firefox: Reference error event is undefined

### ISSUE THREAD

**Issue by eoghanTadhg** [enove/NoSLB#96]
Recieving this error on all click events on the app.
I'm assuming Firefox does not like this:

`'click .selector': function (event) {...`

@micchickenburger , happen to have any insight into this?
My instinct would be to replace all the click events with jquery on template `onRendered` but perhaps you have a better idea?

**Comment by micchickenburger** [comment]
Resolved in 332d4754b3883f0500cb7fc4c24d8b03c77907c1
