### ISSUE TITLE
UI Improvements to WCASA Work section

### ISSUE THREAD

**Issue by micchickenburger** [enove/NoSLB#98]
I noticed some visual improvements that could be made to the WCASA Work section:
- Text on button "Back to Top of Article" blends with background color
- Neither the "Back to Top of Article" nor the "Read More" buttons should display where there is little content.
- Delete and edit admin buttons I added need to be positioned properly along with the print button
- Note that the styles I added in /packages/wcasa:work/lib/templates/work.less at the bottom may need to be relocated based on your master design.
- The hover effect for editing a work section title could use some UX help :)
- Buttons may need to be styled differently, especially "save" button when editing a work section.

**Comment by micchickenburger** [comment]
Furthermore, there is too much spacing between list items.  Headers should probably have greater margins.  Blockquotes should indent, and have some sort of quote appear (in the background?) to illustrate it's a blockquote.

**Comment by eoghanTadhg** [comment]
This has been corrected over numerous commits.
